-- AlterTable
ALTER TABLE "Bookings" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "travelDate" SET DATA TYPE TEXT,
ALTER COLUMN "returnDate" SET DATA TYPE TEXT;
