const flightDatas = [
  {
    id: 1,
    departureAirport: "SAW",
    arrivalAirport: "AYT",
    departureCity: "Istanbul",
    arrivalCity: "Antalya",
    flightDuration: "3h 35m",
    departureTime: "11:00 PM",
    arrivalTime: "12:35 AM",
    stops: "direct",
    returnDepartureTime: "2:30 PM",
    returnFlightDuration: "3h 10m",
    returnArrivalTime: "5:40 PM",
    price: 2550,
  },
  {
    id: 2,
    departureAirport: "CDG",
    arrivalAirport: "BCN",
    departureCity: "Paris",
    arrivalCity: "Barcelona",
    flightDuration: "2h 15m",
    departureTime: "9:45 AM",
    arrivalTime: "11:00 AM",
    stops: "direct",
    returnDepartureTime: "1:30 PM",
    returnFlightDuration: "2h 00m",
    returnArrivalTime: "3:30 PM",
    price: 2200,
  },
  {
    id: 3,
    departureAirport: "LAX",
    arrivalAirport: "JFK",
    departureCity: "Los Angeles",
    arrivalCity: "New York",
    flightDuration: "5h 30m",
    departureTime: "3:00 PM",
    arrivalTime: "8:30 PM",
    stops: "1 stop",
    returnDepartureTime: "9:00 AM",
    returnFlightDuration: "5h 45m",
    returnArrivalTime: "3:15 PM",
    price: 2800,
  },
  {
    id: 4,
    departureAirport: "SFO",
    arrivalAirport: "SEA",
    departureCity: "San Francisco",
    arrivalCity: "Seattle",
    flightDuration: "2h 00m",
    departureTime: "8:15 AM",
    arrivalTime: "10:15 AM",
    stops: "direct",
    returnDepartureTime: "12:30 PM",
    returnFlightDuration: "1h 45m",
    returnArrivalTime: "2:15 PM",
    price: 1500,
  },
  {
    id: 5,
    departureAirport: "ATL",
    arrivalAirport: "MIA",
    departureCity: "Atlanta",
    arrivalCity: "Miami",
    flightDuration: "2h 30m",
    departureTime: "10:30 AM",
    arrivalTime: "1:00 PM",
    stops: "direct",
    returnDepartureTime: "3:45 PM",
    returnFlightDuration: "2h 15m",
    returnArrivalTime: "6:00 PM",
    price: 1800,
  },
  {
    id: 6,
    departureAirport: "ORD",
    arrivalAirport: "DFW",
    departureCity: "Chicago",
    arrivalCity: "Dallas",
    flightDuration: "3h 00m",
    departureTime: "1:45 PM",
    arrivalTime: "4:45 PM",
    stops: "1 stop",
    returnDepartureTime: "6:30 AM",
    returnFlightDuration: "3h 15m",
    returnArrivalTime: "9:45 AM",
    price: 2100,
  },
  {
    id: 7,
    departureAirport: "DEN",
    arrivalAirport: "PHX",
    departureCity: "Denver",
    arrivalCity: "Phoenix",
    flightDuration: "2h 45m",
    departureTime: "11:00 AM",
    arrivalTime: "1:45 PM",
    stops: "direct",
    returnDepartureTime: "4:15 PM",
    returnFlightDuration: "2h 30m",
    returnArrivalTime: "6:45 PM",
    price: 1900,
  },
  {
    id: 8,
    departureAirport: "MSP",
    arrivalAirport: "BOS",
    departureCity: "Minneapolis",
    arrivalCity: "Boston",
    flightDuration: "4h 15m",
    departureTime: "2:15 PM",
    arrivalTime: "6:30 PM",
    stops: "1 stop",
    returnDepartureTime: "8:00 AM",
    returnFlightDuration: "4h 00m",
    returnArrivalTime: "12:00 PM",
    price: 2400,
  },
  {
    id: 9,
    departureAirport: "LAS",
    arrivalAirport: "MCO",
    departureCity: "Las Vegas",
    arrivalCity: "Orlando",
    flightDuration: "4h 45m",
    departureTime: "5:30 AM",
    arrivalTime: "10:15 AM",
    stops: "1 stop",
    returnDepartureTime: "11:30 AM",
    returnFlightDuration: "5h 15m",
    returnArrivalTime: "4:45 PM",
    price: 2600,
  },
  {
    id: 10,
    departureAirport: "PHL",
    arrivalAirport: "IAH",
    departureCity: "Philadelphia",
    arrivalCity: "Houston",
    flightDuration: "3h 30m",
    departureTime: "8:00 AM",
    arrivalTime: "11:30 AM",
    stops: "direct",
    returnDepartureTime: "1:45 PM",
    returnFlightDuration: "3h 15m",
    returnArrivalTime: "5:00 PM",
    price: 2000,
  },
  {
    id: 11,
    departureAirport: "SYD",
    arrivalAirport: "MEL",
    departureCity: "Sydney",
    arrivalCity: "Melbourne",
    flightDuration: "1h 30m",
    departureTime: "6:30 AM",
    arrivalTime: "8:00 AM",
    stops: "direct",
    returnDepartureTime: "10:45 AM",
    returnFlightDuration: "1h 15m",
    returnArrivalTime: "12:00 PM",
    price: 1200,
  },
  {
    id: 12,
    departureAirport: "AMS",
    arrivalAirport: "FRA",
    departureCity: "Amsterdam",
    arrivalCity: "Frankfurt",
    flightDuration: "1h 45m",
    departureTime: "3:15 PM",
    arrivalTime: "4:00 PM",
    stops: "direct",
    returnDepartureTime: "7:30 AM",
    returnFlightDuration: "1h 30m",
    returnArrivalTime: "8:00 AM",
    price: 1400,
  },
  {
    id: 13,
    departureAirport: "HKG",
    arrivalAirport: "NRT",
    departureCity: "Hong Kong",
    arrivalCity: "Tokyo",
    flightDuration: "4h 00m",
    departureTime: "12:00 PM",
    arrivalTime: "4:00 PM",
    stops: "1 stop",
    returnDepartureTime: "6:45 PM",
    returnFlightDuration: "4h 30m",
    returnArrivalTime: "11:15 PM",
    price: 2900,
  },
  {
    id: 14,
    departureAirport: "MIA",
    arrivalAirport: "LHR",
    departureCity: "Miami",
    arrivalCity: "London",
    flightDuration: "8h 45m",
    departureTime: "7:30 PM",
    arrivalTime: "4:15 AM",
    stops: "1 stop",
    returnDepartureTime: "11:00 AM",
    returnFlightDuration: "8h 30m",
    returnArrivalTime: "7:30 PM",
    price: 3500,
  },
  {
    id: 15,
    departureAirport: "BKK",
    arrivalAirport: "SIN",
    departureCity: "Bangkok",
    arrivalCity: "Singapore",
    flightDuration: "2h 30m",
    departureTime: "9:00 AM",
    arrivalTime: "11:30 AM",
    stops: "direct",
    returnDepartureTime: "2:45 PM",
    returnFlightDuration: "2h 15m",
    returnArrivalTime: "5:00 PM",
    price: 2000,
  },
];

export default flightDatas;
